### ISSUE TITLE
Add last HTTP request info to ScenarioStateContext

### ISSUE THREAD

**Issue by akazimirski** [Ragin-LundF/bbd-cucumber-gherkin-lib#37]
Right now there is a last HTTP response stored in ScenarioStateContext.latestResponse. 
There is a need to have corresponding HTTP request as well.

**Comment by Ragin-LundF** [comment]
To set a body, it is possible to use:
```gherkin
Scenario:
  Given that the body of the request is
    """
    {
      "key": "value"
    }
    """
```

or

```gherkin
Scenario:
  Given that the file {string} is used as the body
```

If it is required to access the request body in custom matchers, this can be done with:

```java
ScenarioStateContext.current().getEditableBody()
```
